apiVersion: v1
kind: Service
metadata:
  name: grpc-greeter-backend
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 8080
    targetPort: 9000
    protocol: TCP
    name: http2
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: grpc-greeter-backend
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-greeter-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-greeter-backend
    spec:
      - name: greeter
        image: eu.gcr.io/sa-game-206414/greeter-backend:v1
        ports:
          - containerPort: 9000