apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-greeter
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9100
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-greeter
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-greeter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-greeter
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9100",
          "--service=hellohorld3.endpoints.sa-game-206414.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:9000"
        ]
        ports:
          - containerPort: 9100
      - name: greeter
        image: eu.gcr.io/sa-game-206414/greeter-service:v1
        ports:
          - containerPort: 8000