// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HelloWorldBackend.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Backend.Helloworld {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class GreeterBackend
  {
    static readonly string __ServiceName = "backend.helloworld.GreeterBackend";

    static readonly grpc::Marshaller<global::Backend.Helloworld.BackendHelloRequest> __Marshaller_BackendHelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Backend.Helloworld.BackendHelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Backend.Helloworld.BackendHelloReply> __Marshaller_BackendHelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Backend.Helloworld.BackendHelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Backend.Helloworld.BackendHelloRequest, global::Backend.Helloworld.BackendHelloReply> __Method_SayHelloFromBackend = new grpc::Method<global::Backend.Helloworld.BackendHelloRequest, global::Backend.Helloworld.BackendHelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHelloFromBackend",
        __Marshaller_BackendHelloRequest,
        __Marshaller_BackendHelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Backend.Helloworld.HelloWorldBackendReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GreeterBackend</summary>
    public abstract partial class GreeterBackendBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Backend.Helloworld.BackendHelloReply> SayHelloFromBackend(global::Backend.Helloworld.BackendHelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GreeterBackend</summary>
    public partial class GreeterBackendClient : grpc::ClientBase<GreeterBackendClient>
    {
      /// <summary>Creates a new client for GreeterBackend</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GreeterBackendClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GreeterBackend that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GreeterBackendClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GreeterBackendClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GreeterBackendClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Backend.Helloworld.BackendHelloReply SayHelloFromBackend(global::Backend.Helloworld.BackendHelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloFromBackend(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Backend.Helloworld.BackendHelloReply SayHelloFromBackend(global::Backend.Helloworld.BackendHelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHelloFromBackend, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Backend.Helloworld.BackendHelloReply> SayHelloFromBackendAsync(global::Backend.Helloworld.BackendHelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloFromBackendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Backend.Helloworld.BackendHelloReply> SayHelloFromBackendAsync(global::Backend.Helloworld.BackendHelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHelloFromBackend, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GreeterBackendClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GreeterBackendClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GreeterBackendBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHelloFromBackend, serviceImpl.SayHelloFromBackend).Build();
    }

  }
}
#endregion
